### PR TITLE
File Added: automated-robot-tests.yml

### LINKED ISSUE #73: CI: robot tests
update: 

- [x] create .github/workflows/automated-robot-tests.yml 
- [x] refer: https://github.com/marketplace/actions/robot-framework or https://github.com/marketplace/actions/robot-framework-action
- [x] implement them
- [x] make sure the below code is in the workflow (.yml) file

```
on:
  pull_request:
  push: 
```

### PR DESCRIPTION
**Pull request by RedValis**
## Related Issue(s)

Resolves #73 

.github/workflows/automated-robot-tests.yml created 

- [x] I have followed the repository's contribution guidelines.
- [x] I have added necessary documentation or updated existing documentation.
- [x] My code follows the established code style and formatting of the project.
- [x] I have tested my changes and they function as expected.
- [x] I have added suitable unit tests (if applicable).

### CODE REVIEW

**Comment by RedValis** [comment]
Closed until further testing

**Comment by RedValis** [comment]
Tests pass, workflow does as intended

**Comment by Nasfame** [comment]
@RedValis tests are failing: https://github.com/DeCenter-AI/decenter-ai.streamlit.app/actions/runs/6631190185

**Comment by Nasfame** [comment]
@RedValis no worries i ill help u out

**Pull request closed without merging**
