### PR TITLE
ci: robot

### PR DESCRIPTION
**Pull request by Nasfame**
## Related Issue(s)

For: #73 
Overrides: #76 

## Proposed Changes

[//]: # '[List down the specific changes you have made in this pull request.]'

- [x]
- [x]

## Checklist

- [x] I have followed the repository's contribution guidelines.
- [x] I have added necessary documentation or updated existing documentation.
- [x] My code follows the established code style and formatting of the project.
- [x] I have tested my changes and they function as expected.
- [x] I have added suitable unit tests (if applicable).

## To-Do

- [ ]

### CODE REVIEW

**Comment by Nasfame** [comment]
@RedValis checkout the ci, and fix it

**Comment by Nasfame** [comment]
@RedValis fix the ci

**Comment by RedValis** [comment]
> @RedValis fix the ci

@Nasfame 
There seems to be no issue with the code itself, the streamlit session randomly terminates 2 minutes in

**Comment by Nasfame** [comment]
@RedValis what are u referreing to , is it the ci workflow or robot?

**Comment by RedValis** [comment]
@Nasfame workflow, streamlit local host starts up, then terminates, I'll work on it when I'm free

**Pull request merged**
